export {
    SITE_URL,
    SITE_NAME,
    DEFAULT_OG_IMAGE,
    SUPPORT_EMAIL,
    SUPPORT_PHONE,
    BUSINESS_COORDINATES,
    BUSINESS_LOCATION,
    BUSINESS_HOURS,
    BUSINESS_PHONE,
    BUSINESS_PHONE_DISPLAY,
    BUSINESS_WHATSAPP_NUMBER,
    BUSINESS_EMAIL_NOTE,
    buildLocalBusinessSchema,
    buildOrganizationSchema,
    buildWebSiteSchema,
    SOCIAL_PROFILES,
    slugify,
    formatSlugTitle,
    formatBrandName,
    absoluteUrl,
    resolveOgImage,
    getEffectivePrice,
    getEffectiveStock,
    buildProductSeo,
    buildCategorySeo,
    buildBrandSeo,
} from '../../shared/prerender.js';
