export {
    SITE_URL,
    SITE_NAME,
    DEFAULT_OG_IMAGE,
    SUPPORT_EMAIL,
    SUPPORT_PHONE,
    SOCIAL_PROFILES,
    slugify,
    formatSlugTitle,
    formatBrandName,
    absoluteUrl,
    resolveOgImage,
    getEffectivePrice,
    getEffectiveStock,
    buildProductSeo,
    buildCategorySeo,
    buildBrandSeo,
} from '../../shared/prerender.js';
